baseurl = "https://getsling.com/blog/"
languageCode = "en-us"
theme = "hugo-strata-theme"
title = "SCHEDULING MADE EASY"
[[menu.main]]
name = "GETSLING"
url = "https://getsling.com"
weight = 0
[[menu.main]]
name = "SIGNUP"
url = "https://sling.is/user/register"
weight = 10
[[menu.main]]
name = "FEATURES"
url = "https://getsling.com/features.html"
weight = 10
[[menu.main]]
name = "PRICING (Free) "
url = "https://getsling.com/pricing.html"
weight = 10
[[menu.main]]
name = "LOGIN"
url = "https://sling.is/"
weight = 10
[params]
cover = "/blog/forestryio/images/cafe.jpeg"
date_format = "Mon, Jan 2, 2006"
[params.about]
content = "Sling is a shift scheduling and communication software for retail and restaurants. Built around four main features: shifts, tasks, messages and newsfeed, it allows managers to organize all aspects of their work on a single platform."
hide = false
title = "Sling is the easiest way to schedule and communicate with your employees. For free!"
[params.contact]
hide = true
[params.sidebar]
avatar = "logo.png"
bio = "**Shift scheduling made easy!**"
facebook = "SlingScheduling"
github = "gangverk"
[taxonomies]
tag = "tags"
