baseurl = "https://getsling.com/blog/"
languageCode = "en-us"
theme = "hugo-strata-theme"
title = "SCHEDULING MADE EASY"
[[menu.main]]
name = "GETSLING"
url = "https://getsling.com"
weight = 0
[[menu.main]]
name = "FEATURES"
url = "https://getsling.com/features.html"
weight = 10
[[menu.main]]
name = "PRICING"
url = "https://getsling.com/pricing.html"
weight = 10
[[menu.main]]
name = "SIGNUP"
url = "https://sling.is/user/register"
weight = 10
[[menu.main]]
name = "LOGIN"
url = "https://sling.is/"
weight = 10
[params]
cover = "/blog/forestryio/images/cafe.jpeg"
date_format = "Mon, Jan 2, 2006"
[params.about]
content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."
hide = false
title = "Sling is the easiest way to schedule and communicate with your employees. For free!"
[params.contact]
hide = true
[params.sidebar]
avatar = "logo.png"
bio = "**Shift scheduling made easy!**"
facebook = "SlingScheduling"
github = "gangverk"
[taxonomies]
tag = "tags"
