---
upload_path: "/static/forestryio/images"
frontmatter_file_url_template: "/blog/forestryio/images"
body_file_url_template: "/blog/forestryio/images"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  post:
    default_front_matter_template: post
version: '0.17'
